import {
  SiPython,
  SiJavascript,
  SiTypescript,
  SiHtml5,
  SiTailwindcss,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiDjango,
  SiFlask,
  SiJupyter,
  SiPandas,
  SiScikitlearn,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiDocker,
  SiVercel,
  SiRender,
  SiPostgresql,
  SiSqlite,
} from "react-icons/si";

import { FaJava, FaDatabase, FaChartBar, FaCss3Alt } from "react-icons/fa6";
import { TbApi, TbMath } from "react-icons/tb";
import { VscVscode } from "react-icons/vsc";
import { IconType } from "react-icons";

export const skillIconsMap: Record<string, IconType> = {
  FaJava,
  SiPython,
  SiJavascript,
  SiTypescript,
  SiHtml5,
  FaCss3Alt,
  SiTailwindcss,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiDjango,
  SiFlask,
  TbApi,
  SiJupyter,
  SiPandas,
  SiScikitlearn,
  FaChartBar,
  TbMath,
  FaDatabase,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiDocker,
  SiVercel,
  SiRender,
  VscVscode,
  SiPostgresql,
  SiSqlite,
};
